// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwhrbldhzxkizjzsbbjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aHJibGRoenhraXpqenNiYmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMjM2NzcsImV4cCI6MjA1MjU5OTY3N30.l_BGPPEtgPEnkMaK_JsOcPjHu_V7_hAEp5sWa5dFIlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);